### ISSUE TITLE
Extracting residuals

### ISSUE THREAD

**Issue by bzocc** [ianfiske/unmarked#19]
Would anyone have any recommendations for extracting residuals for an occ object?  Using residuals (x) produces residuals for every detection event, but I am interested in extracting residuals for only the occupancy process.  The entire model fits several covariates for detection and occupancy, but I would like to plot the residuals for the model having a single residual for each site.  Is this possible?  Am I thinking about this incorrectly?  Thanks!

**Comment by ianfiske** [comment]
I'm not really sure off-hand of the correct way to do this since you don't observe a site-level occurrence.  A residual is observed minus fitted, so what would you use for observed?  Maybe the empirical Bayes predictor?  You might also be fine just aggregating your detection-level residuals within each site -- maybe the mean?

**Comment by ianfiske** [comment]
no update on this in a while -- i'm closing.
